### ISSUE TITLE
bookshelves duplication from Items

### ISSUE THREAD

**Issue by Blueeyestar** [InventivetalentDev/Bookshelves#15]
Good day, your bookshelves is great, but unfortunately we have found a huge problem with it.
We also use the plugin EPIC BackPacks 1.1.45c. If you now have such a backpack that is filled and clicks on your bookshelf 'writes the backpack in the bookshelf inventory. You double the items with it. can you fix that?

https://www.spigotmc.org/resources/%E2%9C%85best-backpack-plugin%E2%9C%85-epic-backpacks.28981/

**Comment by InventivetalentDev** [comment]
Please use the issue template.
