### ISSUE TITLE
Bookshelf can not load after updating LWC

### ISSUE THREAD

**Issue by ErythroCraft** [InventivetalentDev/Bookshelves#26]
## What steps will reproduce the problem?  
1. Remove LWCX
2. Updating LWC to v.5.0.16 #80
3. Restarting server

##Desciption:
  So. I'm using Bookshelf on my spigot server since first version. Yesterday I updated [LWC](https://www.iani.de/jenkins/job/LWC/). 
  After restarting my server the hook has an misstake or can not finish. Please read the [Error](https://pastebin.com/92CDYZ5P).
##Server:
  Plugin version: 1.6.0-SNAPSHOT
  Server version: 3493-Spigot-b081915-9d46b56 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT)
  LWC version: LWC v5.0.16 #80
  
After updating Bookshelf does not working.
Maybe you can fix this.

**Comment by Th3Shadowbroker** [comment]
I had a look at the logfile and it seems your using [Bookshelf](https://github.com/LOOHP/Bookshelf) and not Bookshelves. You might want to report that problem [here](https://github.com/LOOHP/Bookshelf/issues).

**Comment by ErythroCraft** [comment]
Oh sorry. That is my misstake. I'm using an other plugin called same.
But, maybe you can make it better.
https://www.spigotmc.org/resources/bookshelf-store-books-inside-enchantment-table-boosting-supports-protection-plugins.75804/

**Comment by ErythroCraft** [comment]
I close this issue, because it isn't the right side.
