### ISSUE TITLE
Bookshelves contents disappear 

### ISSUE THREAD

**Issue by Bet1K** [InventivetalentDev/Bookshelves#8]
Bookshelves contents disappear, perhaps I typed /reload on accident in another world, but all my shelves are empty now, 1-3 days after filling them up. I saw someone else did the same thing but if you could somehow implement back ups?

**Comment by Th3Shadowbroker** [comment]
Hi @Bet1K,
the issue you described isn't new. Reloading is a big problem as Bookshelves stores only the locations of the blocks and writes the inventory to the blocks metadata when loaded. When you reload your server, all plugins get reloaded and Bookshelves loses the locations. I'll see if can find a "leight" way to prevent data-loss on reload.

**Comment by Th3Shadowbroker** [comment]
So...I had a look at the code and found a way. See #9 for details 🙂

**Comment by InventivetalentDev** [comment]
Awesome! :)
